"""`_apply_text_transforms` must preserve chapter-marker pauses.

The Carl Capítulo 1 regression survived two pause-fix commits because
the pre-tts cache on disk was generated by `_apply_text_transforms`,
which regenerates `chapter.speech_text` from the raw `chapter.text`
(no cues) — bypassing the cues that `_prepare_speech_text` added
during parsing. Without a second `apply_structural_speech_cues` pass
inside the transform pipeline, every "<N> |" marker and chapter title
ellipsis was lost.

This test pins the second-pass call at the source level so a future
refactor cannot silently regress the fix.
"""

from __future__ import annotations

import inspect
import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from main import ConverterApplication


class TestApplyTextTransformsPreservesPauses(unittest.TestCase):
    def test_apply_structural_cues_called_after_strip_inline_markdown(self):
        """Source-level guard: after `strip_inline_markdown` builds the
        candidate `speech_text`, `_apply_text_transforms` MUST call
        `apply_structural_speech_cues` again so the pre-tts cache keeps
        the chapter announcements and `<N> |` pauses."""
        src = inspect.getsource(ConverterApplication._apply_text_transforms)
        self.assertIn("strip_inline_markdown", src)
        self.assertIn("apply_structural_speech_cues", src)
        # Must be called on `speech_text` (i.e. after the markdown strip),
        # not just on `final_text` — otherwise the cleanup undoes the cues.
        self.assertIn("speech_text = ", src)


class TestApplyStructureToReaderPreservesPauses(unittest.TestCase):
    """`_apply_structure_to_reader` rebuilds Chapter objects after
    `_apply_text_transforms` ran, throwing away the cued speech_text
    in the process. Without re-stamping the cues here, pre-tts cache
    loses every pause regardless of how many earlier passes added them.
    """

    def test_apply_structural_cues_called_in_structure_to_reader(self):
        src = inspect.getsource(ConverterApplication._apply_structure_to_reader)
        self.assertIn("apply_structural_speech_cues", src)
        # Must be applied to the speech_text being assigned to the new
        # Chapter object, not somewhere unrelated.
        self.assertIn("speech_text =", src)


if __name__ == "__main__":
    unittest.main()
