"""Log harvester + anomaly surface for the Epub-to-Mp3 app.

Designed to run unattended after a conversion or CI run and surface
the things a human would notice and act on:

- Wrong-language audio symptoms (sample-rate mismatch, fallback events).
- Slow chapters (chars/sec well below the engine baseline).
- Retries / silent fallbacks (Edge → Piper / Kokoro / Coqui).
- Validation failures (missing MP3s, duration outliers, dedup hits).
- CI failures (last failed step + first failure line).

Inputs (all optional — missing sources are skipped silently):
- Per-conversion runtime metrics:
    `<output_dir>/_runtime_metrics.jsonl`
    `<cache_dir>/_runtime_metrics.jsonl`
- Persistent session log: `.logs/conversions.jsonl`
- Free-form text logs in `/tmp/carl-conversion/*.log` (or any path
  passed via --log-glob).
- ffprobe sample rate of every MP3 in `output/<book>/`.

Output: a single Markdown report on stdout (or `--out FILE`) that
lists the issues bucketed by severity, plus the file path of the
underlying log so a human can dig deeper. Exits 0 always; the report
itself is the signal.

Usage:
    python scripts/analyze_logs.py [--book "Title"] [--log-glob PATTERN]
                                   [--out PATH] [--ci-runs N]

Wired in `mise.toml` as `mise run analyze-logs`.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Optional

ROOT = Path(__file__).resolve().parents[1]


@dataclass
class Issue:
    severity: str
    title: str
    detail: str
    source: str = ""


@dataclass
class Report:
    issues: list[Issue] = field(default_factory=list)
    stats: dict[str, str] = field(default_factory=dict)

    def add(self, severity: str, title: str, detail: str, source: str = "") -> None:
        self.issues.append(Issue(severity, title, detail, source))


# ---------------------------------------------------------------------------
# Source 1: ffprobe per-MP3 sample rate (fingerprints which engine spoke)
# ---------------------------------------------------------------------------


def _ffprobe_sample_rate(path: Path) -> Optional[int]:
    """Return the first audio stream sample rate in Hz, or None on error."""
    if shutil.which("ffprobe") is None:
        return None
    try:
        result = subprocess.run(
            (
                "ffprobe",
                "-v",
                "error",
                "-select_streams",
                "a:0",
                "-show_entries",
                "stream=sample_rate",
                "-of",
                "default=nw=1:nk=1",
                str(path),
            ),
            capture_output=True,
            text=True,
            timeout=5,
        )
        line = result.stdout.strip().splitlines()[0] if result.stdout.strip() else ""
        return int(line) if line.isdigit() else None
    except (subprocess.SubprocessError, OSError, ValueError):
        return None


def scan_output_engine_consistency(book_dir: Path, report: Report) -> None:
    """Flag MP3s whose sample rate diverges from the rest of the book.

    A pt-BR audiobook generated by Edge should be uniformly 24 kHz. A
    single 16 kHz file means Piper sneaked in (the Carl Capa
    regression). We compare each chapter to the modal rate.
    """
    mp3s = sorted(p for p in book_dir.glob("*.mp3") if p.is_file())
    if not mp3s:
        return
    rates: list[tuple[Path, Optional[int]]] = [(m, _ffprobe_sample_rate(m)) for m in mp3s]
    valid = [r for _, r in rates if r is not None]
    if not valid:
        return
    modal_rate, modal_count = Counter(valid).most_common(1)[0]
    report.stats["audio_files"] = str(len(mp3s))
    report.stats["modal_sample_rate"] = f"{modal_rate} Hz ({modal_count}/{len(valid)})"

    outliers = [(p, r) for p, r in rates if r is not None and r != modal_rate]
    if outliers:
        engine_hint = {16000: "Piper", 22050: "Coqui", 24000: "Edge/Kokoro"}
        for path, rate in outliers[:10]:
            hint = engine_hint.get(rate or 0, "unknown")
            report.add(
                "HIGH",
                "Sample-rate outlier in output",
                f"{path.name}: {rate} Hz (likely {hint}); rest of book is {modal_rate} Hz",
                source=str(path),
            )


# ---------------------------------------------------------------------------
# Source 2: runtime metrics jsonl (per-event from the converter)
# ---------------------------------------------------------------------------


def _iter_runtime_metrics(book_dir: Path) -> Iterable[dict]:
    for candidate in (book_dir / "_runtime_metrics.jsonl",):
        if not candidate.exists():
            continue
        try:
            for line in candidate.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if not line:
                    continue
                try:
                    yield json.loads(line)
                except json.JSONDecodeError:
                    continue
        except OSError:
            continue


def scan_runtime_metrics(book_dir: Path, report: Report) -> None:
    """Surface slow chapters, retries, and engine fallbacks."""
    events = list(_iter_runtime_metrics(book_dir))
    if not events:
        return

    # Slow chapters: synthesis_complete with chars/sec below the engine floor.
    floors = {"edge": 60, "kokoro": 25, "piper": 35, "coqui": 20}
    by_engine_chars: dict[str, list[float]] = defaultdict(list)
    fallback_count = Counter()
    retry_count = Counter()
    timeout_count = 0

    for ev in events:
        kind = ev.get("event") or ""
        engine = (ev.get("engine") or "").lower()
        if kind == "chapter_synthesised":
            cps = float(ev.get("chars_per_second") or 0)
            if engine and cps:
                by_engine_chars[engine].append(cps)
                floor = floors.get(engine, 0)
                if floor and cps < floor:
                    report.add(
                        "MEDIUM",
                        f"Slow synthesis on {engine}",
                        f"chapter {ev.get('chapter')}: {cps:.1f} chars/s (floor {floor})",
                        source=str(book_dir / "_runtime_metrics.jsonl"),
                    )
        elif kind == "engine_fallback":
            fallback_count[(ev.get("from_engine"), ev.get("to_engine"))] += 1
        elif kind == "chapter_retry":
            retry_count[engine or "unknown"] += 1
        elif kind == "chapter_timeout":
            timeout_count += 1

    for (frm, to), count in fallback_count.most_common():
        sev = "HIGH" if (frm == "edge" and to == "piper") else "MEDIUM"
        report.add(
            sev,
            f"Engine fallback {frm}→{to}",
            f"{count} chapter(s) — verify the user did not pass --fallback-engine none",
            source=str(book_dir / "_runtime_metrics.jsonl"),
        )

    for engine, count in retry_count.most_common():
        if count > 3:
            report.add(
                "MEDIUM",
                f"Repeated retries on {engine}",
                f"{count} chapter retries (look for slow_mode / rate_limit events around them)",
                source=str(book_dir / "_runtime_metrics.jsonl"),
            )

    if timeout_count:
        report.add(
            "MEDIUM",
            "Chapter timeouts",
            f"{timeout_count} chapter(s) hit the per-chapter hard timeout",
            source=str(book_dir / "_runtime_metrics.jsonl"),
        )

    for engine, samples in by_engine_chars.items():
        if samples:
            avg = sum(samples) / len(samples)
            report.stats[f"avg_chars_per_sec_{engine}"] = f"{avg:.1f} ({len(samples)} ch)"


# ---------------------------------------------------------------------------
# Source 3: session log .logs/conversions.jsonl
# ---------------------------------------------------------------------------


def scan_session_log(report: Report, last_n: int = 5) -> None:
    log_path = ROOT / ".logs" / "conversions.jsonl"
    if not log_path.exists():
        return
    try:
        lines = log_path.read_text(encoding="utf-8").splitlines()[-last_n:]
    except OSError:
        return
    failed = []
    for line in lines:
        line = line.strip()
        if not line:
            continue
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        if entry.get("outcome") not in {"success", "skipped"}:
            failed.append(entry)
    if failed:
        for entry in failed[-3:]:
            report.add(
                "HIGH",
                f"Recent run failed: {entry.get('book_title', '?')}",
                f"engine={entry.get('engine')} outcome={entry.get('outcome')} "
                f"chapters={entry.get('chapters_failed', 0)}/{entry.get('chapters_total', 0)} "
                f"failed",
                source=str(log_path),
            )


# ---------------------------------------------------------------------------
# Source 4: free-form text logs (for things metrics don't capture yet)
# ---------------------------------------------------------------------------

_LOG_PATTERNS = [
    (re.compile(r"❌|ERROR|Traceback|fail\(\d+\)"), "MEDIUM", "Error / failure in log"),
    (re.compile(r"piper", re.I), "LOW", "Piper mention"),  # cross-checked vs --fallback-engine
    (
        re.compile(r"falling back to|switching to (piper|coqui|kokoro)", re.I),
        "HIGH",
        "Engine fallback announced in log",
    ),
    (re.compile(r"rate.?limit|429|throttle", re.I), "MEDIUM", "Rate limit"),
    (re.compile(r"timeout|timed out", re.I), "LOW", "Timeout mention"),
    (re.compile(r"slow.?mode|SLOW_DETECTED", re.I), "LOW", "Slow mode triggered"),
    (re.compile(r"Discrepância|MISMATCH|wrong.?language", re.I), "HIGH", "Language mismatch"),
]


_REPORT_ZERO_RE = re.compile(r"❌\s+[^:]+:\s*0\s*$")


def _is_report_header_zero(line: str) -> bool:
    """True for validation-summary lines like "❌ Missing MP3: 0"."""
    return bool(_REPORT_ZERO_RE.search(line.strip()))


def scan_text_logs(log_globs: list[str], report: Report, max_per_pattern: int = 3) -> None:
    seen: dict[str, int] = defaultdict(int)
    for pattern_glob in log_globs:
        for log_path in sorted(
            Path("/").glob(pattern_glob.lstrip("/"))
            if pattern_glob.startswith("/")
            else Path(".").glob(pattern_glob)
        ):
            if not log_path.is_file():
                continue
            try:
                # Only the tail — old logs are mostly irrelevant.
                lines = log_path.read_text(encoding="utf-8", errors="ignore").splitlines()
            except OSError:
                continue
            tail = lines[-2000:]
            for regex, severity, label in _LOG_PATTERNS:
                key = f"{log_path}:{label}"
                if seen[key] >= max_per_pattern:
                    continue
                for line in tail:
                    if regex.search(line):
                        if label == "Error / failure in log" and _is_report_header_zero(line):
                            continue
                        report.add(severity, label, line.strip()[:240], source=str(log_path))
                        seen[key] += 1
                        if seen[key] >= max_per_pattern:
                            break


# ---------------------------------------------------------------------------
# Source 5: GitHub CI status (last N runs)
# ---------------------------------------------------------------------------


def scan_ci(report: Report, n: int = 3) -> None:
    if shutil.which("gh") is None:
        return
    try:
        result = subprocess.run(
            (
                "gh",
                "run",
                "list",
                "--workflow=CI",
                "--limit",
                str(n),
                "--json",
                "status,conclusion,displayTitle,databaseId,createdAt",
            ),
            capture_output=True,
            text=True,
            timeout=15,
        )
        if result.returncode != 0:
            return
        runs = json.loads(result.stdout or "[]")
    except (subprocess.SubprocessError, json.JSONDecodeError, OSError):
        return
    for run in runs:
        if run.get("conclusion") == "failure":
            report.add(
                "HIGH",
                f"CI failed: {run.get('displayTitle', '?')[:70]}",
                f"run id {run.get('databaseId')}; "
                f"`gh run view {run.get('databaseId')} --log-failed` for details",
                source=f"GitHub CI run {run.get('databaseId')}",
            )


# ---------------------------------------------------------------------------
# Render
# ---------------------------------------------------------------------------

SEVERITY_ORDER = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}


def render(report: Report) -> str:
    lines: list[str] = []
    lines.append("# Log Analysis Report")
    lines.append("")
    if report.stats:
        lines.append("## Stats")
        for k, v in report.stats.items():
            lines.append(f"- **{k}**: {v}")
        lines.append("")
    if not report.issues:
        lines.append("## Issues")
        lines.append("_None._ All sources clean.")
        return "\n".join(lines)
    by_sev = defaultdict(list)
    for issue in report.issues:
        by_sev[issue.severity].append(issue)
    for sev in sorted(by_sev, key=lambda s: SEVERITY_ORDER.get(s, 99)):
        lines.append(f"## {sev}  ({len(by_sev[sev])})")
        for issue in by_sev[sev]:
            lines.append(f"### {issue.title}")
            lines.append(f"- {issue.detail}")
            if issue.source:
                lines.append(f"- _source_: `{issue.source}`")
            lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--book",
        default=None,
        help="Book title (output dir name) to scope output/cache scan to a single conversion.",
    )
    parser.add_argument(
        "--log-glob",
        action="append",
        default=None,
        help="Glob pattern(s) for text logs. Default: /tmp/carl-conversion/*.log + /tmp/*.log",
    )
    parser.add_argument(
        "--ci-runs",
        type=int,
        default=3,
        help="How many recent CI runs to inspect (default 3).",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Write report to file instead of stdout.",
    )
    args = parser.parse_args()

    report = Report()

    output_root = ROOT / "output"
    cache_root = ROOT / ".cache"
    if args.book:
        candidates = [output_root / args.book]
        cache_candidates = [cache_root / args.book]
    else:
        candidates = (
            [p for p in output_root.iterdir() if p.is_dir()] if output_root.exists() else []
        )
        cache_candidates = (
            [p for p in cache_root.iterdir() if p.is_dir()] if cache_root.exists() else []
        )

    for book_dir in candidates:
        if not book_dir.exists():
            continue
        scan_output_engine_consistency(book_dir, report)
    for cache_dir in cache_candidates:
        if not cache_dir.exists():
            continue
        scan_runtime_metrics(cache_dir, report)

    scan_session_log(report)

    log_globs = args.log_glob or ["/tmp/carl-conversion/*.log", "/tmp/*.log"]
    scan_text_logs(log_globs, report)

    scan_ci(report, n=args.ci_runs)

    output = render(report)
    if args.out:
        args.out.write_text(output, encoding="utf-8")
        print(f"Report written to {args.out}")
    else:
        print(output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
