import { API_BASE_URL, POLL_INTERVAL_MS } from '../config';
import {
  ConversionFormValues,
  JobSnapshot,
} from '../types/conversion';

export interface PollOptions {
  intervalMs?: number;
  signal?: AbortSignal;
  onSnapshot?: (snapshot: JobSnapshot) => void;
}

export interface ConversionClient {
  submit(request: ConversionFormValues): Promise<{ jobId: string }>;
  fetch(jobId: string, signal?: AbortSignal): Promise<JobSnapshot>;
  poll(jobId: string, options?: PollOptions): Promise<JobSnapshot>;
}

function buildFormData(values: ConversionFormValues): FormData {
  const formData = new FormData();
  formData.append('file', values.file);
  formData.append('engine', values.engine);
  if (values.voice) {
    formData.append('voice', values.voice);
  }
  if (values.chapters) {
    formData.append('chapters', values.chapters);
  }
  if (values.footnoteMode) {
    formData.append('footnote_mode', values.footnoteMode);
  }
  if (values.language) {
    formData.append('language', values.language);
  }
  return formData;
}

async function parseResponse<T>(response: Response): Promise<T> {
  if (!response.ok) {
    const text = await response.text();
    throw new Error(text || `Backend responded with status ${response.status}`);
  }
  return response.json() as Promise<T>;
}

async function sleep(ms: number, signal?: AbortSignal): Promise<void> {
  if (signal?.aborted) {
    throw new DOMException('Aborted', 'AbortError');
  }

  await new Promise<void>((resolve, reject) => {
    const timeout = setTimeout(() => {
      if (signal) {
        signal.removeEventListener('abort', onAbort);
      }
      resolve();
    }, ms);

    const onAbort = () => {
      clearTimeout(timeout);
      reject(new DOMException('Aborted', 'AbortError'));
    };

    if (signal) {
      signal.addEventListener('abort', onAbort, { once: true });
    }
  });
}

export class HttpConversionClient implements ConversionClient {
  constructor(private readonly baseUrl: string = API_BASE_URL) {}

  private resolve(path: string): string {
    const normalizedBase = this.baseUrl.replace(/\/$/, '');
    const normalizedPath = path.startsWith('/') ? path : `/${path}`;
    return `${normalizedBase}${normalizedPath}`;
  }

  async submit(request: ConversionFormValues): Promise<{ jobId: string }> {
    const response = await fetch(this.resolve('/convert'), {
      method: 'POST',
      body: buildFormData(request),
    });
    return parseResponse<{ jobId: string }>(response);
  }

  async fetch(jobId: string, signal?: AbortSignal): Promise<JobSnapshot> {
    const response = await fetch(this.resolve(`/jobs/${encodeURIComponent(jobId)}`), {
      method: 'GET',
      signal,
    });
    if (response.status === 404) {
      return {
        jobId,
        state: 'queued',
        events: [],
      } satisfies JobSnapshot;
    }
    return parseResponse<JobSnapshot>(response);
  }

  async poll(jobId: string, options: PollOptions = {}): Promise<JobSnapshot> {
    const interval = options.intervalMs ?? POLL_INTERVAL_MS;
    const { signal } = options;

    while (true) {
      const snapshot = await this.fetch(jobId, signal);
      options.onSnapshot?.(snapshot);

      if (snapshot.state === 'finished' || snapshot.state === 'failed') {
        return snapshot;
      }

      await sleep(interval, signal);
    }
  }
}

export class MockConversionClient implements ConversionClient {
  private jobCounter = 0;

  private createMockZip(bookTitle: string): string {
    // Create a simple ZIP-like file with mock MP3 data
    const content = `Mock Audiobook: ${bookTitle}

This is a mock ZIP file containing:
- 001 - Capítulo 1.mp3
- 002 - Capítulo 2.mp3
- 003 - Capítulo 3.mp3

Generated by MockConversionClient for testing purposes.
Date: ${new Date().toISOString()}
`;
    const blob = new Blob([content], { type: 'application/zip' });
    return URL.createObjectURL(blob);
  }

  async submit(request: ConversionFormValues): Promise<{ jobId: string }> {
    this.jobCounter++;
    const jobId = `mock-job-${this.jobCounter}`;
    console.log('[MockClient] Conversion started:', { jobId, request });
    return { jobId };
  }

  async fetch(jobId: string): Promise<JobSnapshot> {
    return {
      jobId,
      state: 'queued',
      events: ['Mock: Job received', 'Mock: Processing started'],
    };
  }

  async poll(jobId: string, options: PollOptions = {}): Promise<JobSnapshot> {
    const bookTitle = 'Livro_de_Exemplo';
    const zipUrl = this.createMockZip(bookTitle);

    const steps: JobSnapshot[] = [
      {
        jobId,
        state: 'running',
        events: [
          '📚 METADADOS DO EBOOK',
          '================================================================',
          '📜 Título: Livro de Exemplo',
          '✍️ Autor: Autor Desconhecido',
          '📊 Capítulos: 3',
          '📝 Total de caracteres: 12,450',
        ],
        chaptersTotal: 3,
        chaptersCompleted: 0,
        progressPercent: 5,
      },
      {
        jobId,
        state: 'running',
        events: [
          '📚 METADADOS DO EBOOK',
          '================================================================',
          '📜 Título: Livro de Exemplo',
          '✍️ Autor: Autor Desconhecido',
          '📊 Capítulos: 3',
          '📝 Total de caracteres: 12,450',
          '',
          '🌐 DETECÇÃO DE IDIOMA',
          '----------------------------------------------------------------',
          '🌐 Idioma principal: pt-BR (confiança: Alta)',
          '   Probabilidade: 95.2%',
          '🔍 Caracteres analisados: 12,450',
        ],
        detectedLanguage: 'pt-BR',
        chaptersTotal: 3,
        chaptersCompleted: 0,
        progressPercent: 15,
      },
      {
        jobId,
        state: 'running',
        events: [
          '📚 METADADOS DO EBOOK',
          '================================================================',
          '📜 Título: Livro de Exemplo',
          '✍️ Autor: Autor Desconhecido',
          '📊 Capítulos: 3',
          '📝 Total de caracteres: 12,450',
          '',
          '🌐 DETECÇÃO DE IDIOMA',
          '----------------------------------------------------------------',
          '🌐 Idioma principal: pt-BR (confiança: Alta)',
          '   Probabilidade: 95.2%',
          '🔍 Caracteres analisados: 12,450',
          '',
          '🎯 Convertendo capítulo 1/3: Capítulo 1',
          'Processando: [██████████░░░░░░░░░░░░░░░░░░░░] 33.3% (1/3) ETA: 45s',
        ],
        detectedLanguage: 'pt-BR',
        chaptersTotal: 3,
        chaptersCompleted: 1,
        currentChapter: 'Capítulo 1',
        progressPercent: 33,
      },
      {
        jobId,
        state: 'running',
        events: [
          '📚 METADADOS DO EBOOK',
          '================================================================',
          '📜 Título: Livro de Exemplo',
          '✍️ Autor: Autor Desconhecido',
          '📊 Capítulos: 3',
          '📝 Total de caracteres: 12,450',
          '',
          '🌐 DETECÇÃO DE IDIOMA',
          '----------------------------------------------------------------',
          '🌐 Idioma principal: pt-BR (confiança: Alta)',
          '   Probabilidade: 95.2%',
          '🔍 Caracteres analisados: 12,450',
          '',
          '🎯 Convertendo capítulo 1/3: Capítulo 1',
          'Processando: [██████████░░░░░░░░░░░░░░░░░░░░] 33.3% (1/3) ETA: 45s',
          '✅ Concluído: 001 - Capítulo 1.mp3',
          '',
          '🎯 Convertendo capítulo 2/3: Capítulo 2',
          'Processando: [████████████████████░░░░░░░░░░] 66.7% (2/3) ETA: 22s',
        ],
        detectedLanguage: 'pt-BR',
        chaptersTotal: 3,
        chaptersCompleted: 2,
        currentChapter: 'Capítulo 2',
        progressPercent: 67,
      },
      {
        jobId,
        state: 'finished',
        events: [
          '📚 METADADOS DO EBOOK',
          '================================================================',
          '📜 Título: Livro de Exemplo',
          '✍️ Autor: Autor Desconhecido',
          '📊 Capítulos: 3',
          '📝 Total de caracteres: 12,450',
          '',
          '🌐 DETECÇÃO DE IDIOMA',
          '----------------------------------------------------------------',
          '🌐 Idioma principal: pt-BR (confiança: Alta)',
          '   Probabilidade: 95.2%',
          '🔍 Caracteres analisados: 12,450',
          '',
          '🎯 Convertendo capítulo 1/3: Capítulo 1',
          'Processando: [██████████░░░░░░░░░░░░░░░░░░░░] 33.3% (1/3) ETA: 45s',
          '✅ Concluído: 001 - Capítulo 1.mp3',
          '',
          '🎯 Convertendo capítulo 2/3: Capítulo 2',
          'Processando: [████████████████████░░░░░░░░░░] 66.7% (2/3) ETA: 22s',
          '✅ Concluído: 002 - Capítulo 2.mp3',
          '',
          '🎯 Convertendo capítulo 3/3: Capítulo 3',
          'Processando: [██████████████████████████████] 100.0% (3/3) ETA: 0s',
          '✅ Concluído: 003 - Capítulo 3.mp3',
          '',
          '📦 Criando arquivo ZIP: Livro_de_Exemplo.zip',
          '✅ Conversão finalizada em 1m 8s',
          '📁 Arquivo disponível: Livro_de_Exemplo.zip (3 capítulos)',
        ],
        detectedLanguage: 'pt-BR',
        chaptersTotal: 3,
        chaptersCompleted: 3,
        currentChapter: 'Capítulo 3',
        progressPercent: 100,
        outputs: [
          { name: 'Livro_de_Exemplo.zip', url: zipUrl },
        ],
      },
    ];

    for (const step of steps) {
      await sleep(1800);
      options.onSnapshot?.(step);
      if (step.state === 'finished') {
        return step;
      }
    }

    return steps[steps.length - 1];
  }
}

export const conversionClient = new HttpConversionClient();
export const mockConversionClient = new MockConversionClient();
